In [2]:
include("../TensorOperations.jl")
using .TensorOperations

## Test 1

In [9]:
A = reshape([1, 3, 2, 4, 5, 7, 6, 8], 2, 2, 2)


2×2×2 Array{Int64, 3}:
[:, :, 1] =
 1  2
 3  4

[:, :, 2] =
 5  6
 7  8

In [10]:
B = [1 ; 0]

2-element Vector{Int64}:
 1
 0

In [11]:
z = A * B

2×1×2 Array{Int64, 3}:
[:, :, 1] =
 1
 3

[:, :, 2] =
 5
 7

## Test 2

In [13]:
x = zeros(Float32, 3, 2, 4)
# Warstwa 1 (k=1)
x[:,:,1] = [1 0;
            2 1;
            3 2] 
# Warstwa 2 (k=2) 
x[:,:,2] = [1 1;
            0 1;
            2 0]

# Warstwa 3 (k=3)
x[:,:,3] = [2 0; 
            1 0; 
            0 1] 

# Warstwa 4 (k=4)
x[:,:,4] = [1 2; 
            0 0; 
            1 1]  
x

3×2×4 Array{Float32, 3}:
[:, :, 1] =
 1.0  0.0
 2.0  1.0
 3.0  2.0

[:, :, 2] =
 1.0  1.0
 0.0  1.0
 2.0  0.0

[:, :, 3] =
 2.0  0.0
 1.0  0.0
 0.0  1.0

[:, :, 4] =
 1.0  2.0
 0.0  0.0
 1.0  1.0

In [14]:
A = Float32[1 0 2 4 6;
            0 1 3 5 7]

2×5 Matrix{Float32}:
 1.0  0.0  2.0  4.0  6.0
 0.0  1.0  3.0  5.0  7.0

In [15]:
b = x*A

3×5×4 Array{Float32, 3}:
[:, :, 1] =
 1.0  0.0   2.0   4.0   6.0
 2.0  1.0   7.0  13.0  19.0
 3.0  2.0  12.0  22.0  32.0

[:, :, 2] =
 1.0  1.0  5.0  9.0  13.0
 0.0  1.0  3.0  5.0   7.0
 2.0  0.0  4.0  8.0  12.0

[:, :, 3] =
 2.0  0.0  4.0  8.0  12.0
 1.0  0.0  2.0  4.0   6.0
 0.0  1.0  3.0  5.0   7.0

[:, :, 4] =
 1.0  2.0  8.0  14.0  20.0
 0.0  0.0  0.0   0.0   0.0
 1.0  1.0  5.0   9.0  13.0